module.exports = {
  docs: {
    "Guías generales": [
      "pautas-para-codigo-abierto",
      "cultura-ingenieril",
      "metodologias-agiles",
      "metodologia-vuelos",
      "programacion-parejas-grupos",
      "herramientas-para-desarrolladores",
      "proyectos-de-codigo-abierto",
      "boilerplate",
      "material-ui",
      "recursos-visuales",
      "redes-sociales",
      "herramientas-para-desarrolladores-ux-ui",
      "devops",
    ],
    "Aprender EOSIO": [
      "aprender-eosio/protocolo-eosio",
      "aprender-eosio/mecanismo-de-consenso",
      "aprender-eosio/uso-de-recursos",
      "aprender-eosio/componentes-eosio",
      "aprender-eosio/cuentas-permisos",
      "aprender-eosio/funciones-importantes",
      "aprender-eosio/llaves-privadas",
      "aprender-eosio/desarrollo-de-dapps",
      "aprender-eosio/cadena-de-bloques-eos",
      "aprender-eosio/contratos-inteligentes",
      "aprender-eosio/contratos-ricardianos",
      "aprender-eosio/seguridad-blockchain",
      "aprender-eosio/nfts-en-eosio",
    ],
    Tutoriales: [
      "tutoriales/contrato-hola-mundo",
      "tutoriales/cpp-moderno",
      "tutoriales/docker",
      "tutoriales/graphql",
      "tutoriales/guia-github",
      "tutoriales/guia-markdown",
      "tutoriales/instalacion-de-nodos",
      "tutoriales/instalacion-de-red-privada",
      "tutoriales/kubernetes",
      "tutoriales/llaves-github",
      "tutoriales/publicacion-de-paquetes",
      "tutoriales/tutorial-flujo-trabajo-git",
      "tutoriales/tutorial-react",
      "tutoriales/como-mintear",
    ],
    Herramientas: [
      "herramientas/glosario",
      "herramientas/linea-de-comando",
      "herramientas/opciones-configuracion-nodeos",
      "herramientas/ejemplos-configuracion-nodeos",
      "herramientas/explorador-de-bloques",
      "herramientas/librerias-sdk",
      "herramientas/plantilla-readme",
      "herramientas/preguntas-frecuentes",
      "herramientas/pow-vs-pos-vs-dpos",
    ],
    Comunidad: [
      "comunidad/redes-eosio",
      "comunidad/canales-de-telegram",
      "comunidad/publicaciones-blog",
      "comunidad/podcasts-eos",
      "comunidad/enlaces-utiles",
    ],
  },
};
